#!/bin/bash

set -e

interactive=0

while true; do
    if [ $# -eq 0 ]; then
	echo $#
	break
    fi
    case "$1" in
	-s | --stop-after-mount)
	    interactive=1
	    shift 1
	    ;;
	-*)
	    echo "Error: Unknown option $1" >&2
	    exit 1
	    ;;
	*)
	    break
	    ;;
    esac
done

loopdev=`sudo losetup --partscan --find --show $1`

sudo mkdir -p /mnt/STBOOT
sudo mkdir -p /mnt/STDATA

sudo mount ${loopdev}p1 /mnt/STBOOT
sudo mount ${loopdev}p2 /mnt/STDATA

echo STBOOT
find /mnt/STBOOT || true
echo --
echo STDATA
find /mnt/STDATA || true
echo --

if [ $interactive -eq 1 ]; then
    echo "mounted at /mnt/STBOOT /mnt/STDATA"
    bash -c 'cd /mnt/; exec bash'
fi

sudo umount /mnt/STBOOT
sudo umount /mnt/STDATA
sudo losetup -d ${loopdev}
